version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 4433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Secret1234
    volumes:
      - tprogData:/var/opt/mssql

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8001:80
    depends_on:
      - mssql
    volumes:
      - ./server/appsettings.Development.json:/app/appsettings.json

volumes:
  tprogData:
    driver: local